### PR TITLE
Integrate MSTeams node sample with app

### PR DESCRIPTION
**Pull request by sdg9**
Specifically combines https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/07.using-adaptive-cards with our project.  

Working in emulator.

Update .env file to be 
```
botFilePath=../orby.bot
botFileSecret=none
MicrosoftAppID=
MicrosoftAppPassword=
```

### CODE REVIEW

**Comment by sdg9** [comment]
poop hate horrible worst idiot garbage

**Comment by wsguede** [comment]
lgtm

**Comment by sdg9** [comment]
^ who still uses lgtm?
poop hate horrible worst idiot garbage

**Comment by sdg9** [comment]
ok taht last one wasnt toxic enough more anger hate grrr screw you bot!!! lol

**Pull request merged**
